version: "2"

services:
    project:
        image: mncedim/php56-apache
        hostname: localhost
        ports:
            - "8081:80"
            - "8443:443"
        volumes:
            - ./_config/ssmtp.conf:/etc/ssmtp/ssmtp.conf:ro
            - ./_config/app.ini:/usr/local/etc/php/conf.d/app.ini:ro
            - ./_config/ssl/cert.pem:/etc/apache2/ssl/cert.pem
            - ./_config/ssl/key.pem:/etc/apache2/ssl/key.pem
            - ./_config/ssl.conf:/etc/apache2/sites-enabled/000-default-ssl.conf
            - .:/var/www/html
        links:
            - db
            - mailhog

    db:
        image: mysql:5.6
        volumes:
            - ./_config/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
            - startup_project_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=mysql
            - MYSQL_DATABASE=startup_project_db
        ports:
            - "3301:3306"
        restart: always

    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - "1025:1025"
            - "8025:8025"
      
volumes:
    startup_project_data:
